version: '3.1'

services:
  #frontend:
   #image: 'josiahgoodson/hackathon-frontend'
    #ports:
     # - 3000:80
    #links:
     # - backend
  backend:
    image: 'josiahgoodson/hackathon-backend'
    volumes:
      - ~/projects/hwx-hackathon-2018/backend:/usr/src/app
    ports:
      - 4000:4000
    links:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pg_pass123!
    volumes:
      - /tmp/data_pg:/var/lib/postgresql/data
    ports:
      - 5432:5432    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080