version: '3.1'

services:
  frontend:
    image: 'josiahgoodson/hackathon-frontend'
    ports:
      - 3000:80
    links:
      - backend
  backend:
    image: 'josiahgoodson/hackathon-backend'
    ports:
      - 4000:4000
    links:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pg_pass123!
    volumes:
      - /data/pg:/var/lib/postgresql/data
    ports:
      - 5432:5432